
public class Driver 
{
	public static void main(String[] args)
	{
		// Employee ID must be generated by us
		// DA and Total Salary must be generated by us
		// Department Name should be generated by us
		// User just inputs the following data Employee Name, Job, Salary, Department ID
		
	}

}
