package companyInformation;
import java.util.*;
public class Driver 
{
	public int[] eid = new int[5]; 
	public static void main(String[] args)
	{
		// Employee ID must be generated by us
		// DA and Total Salary must be generated by us
		// Department Name should be generated by us
		// User just inputs the following data Employee Name, Job, Salary, Department ID
		System.out.println("Enter the Number of Entries");
		Scanner scan = new Scanner(System.in);
		int n = scan.nextInt();
		Employee[] empObjects = new Employee[n];
		Department[] deptObjects = new Department[n];
		
		for(int i=0;i<n;i++)
		{
			System.out.println("Enter the Detals of the Employees\n 1)");
			
		}
		
		
		scan.close();
	}

}
