package companyInformation;
import java.util.*;
import companyInformation.Department;
import companyInformation.Employee;
public class Driver 
{
	public static void main(String[] args)
	{
		int[] eid = new int[5]; 
		// Employee ID must be generated by us
		// DA and Total Salary must be generated by us
		// Department Name should be generated by us
		// User just inputs the following data Employee Name, Job, Salary, Department ID
		System.out.println("Enter the Number of Entries");
		Scanner scan = new Scanner(System.in);
		int n = scan.nextInt();
		
		Employee e = new Employee();
		
		e.checkEmployee("Tejeswara Sai", "Professor", 20000, 100, eid);
		
		for(int i=0;i<n;i++)
		{
			System.out.println("Enter the Detals of the Employees\n 1)");
			
		}
		
		
		scan.close();
	}

}
